### ISSUE TITLE
Sample on-policy trajectories and store in experience buffer

### ISSUE THREAD

**Issue by thiagopbueno** [thiagopbueno/model-aware-policy-optimization#13]
Evaluate a given policy in a given environment for collecting experiences that should be stored in an experience buffer for subsequent use in batch sampling in value fitting, model learning and policy improvement.

**Comment by thiagopbueno** [comment]
Should we use [RolloutWork](https://github.com/ray-project/ray/blob/54d5969ceacabad2741af278ef9ed4db0af66835/python/ray/rllib/evaluation/rollout_worker.py#L53) class to perform Policy Evaluation?

**Comment by thiagopbueno** [comment]
Should we use the [SampleBatch](https://github.com/ray-project/ray/blob/54d5969ceacabad2741af278ef9ed4db0af66835/python/ray/rllib/policy/sample_batch.py#L89) class to handle the experience replay interface?

**Comment by angelolovatto** [comment]
I believe this should be handled in an `Optimizer`. The [SyncReplayOptimizer](https://github.com/ray-project/ray/blob/master/python/ray/rllib/optimizers/sync_replay_optimizer.py) coordinates the collection of samples in the environment and stores then in an `ExperienceReplay` buffer. It might be useful to subclass it if we wish to have separate experience buffers for real and synthetic data
