### ISSUE TITLE
Create rllib.Optimizer subclass to handle separate experience buffers

### ISSUE THREAD

**Issue by angelolovatto** [thiagopbueno/model-aware-policy-optimization#16]
Questions:
* Should we have a buffer for synthetic only or a buffer that mixes both real and synthetic data?

Tasks
* [ ] create `optimizers` subfolder
* [ ] define a replay buffer for environment samples, D_env
* [ ] define a replay buffer for model samples, D_model

**Comment by thiagopbueno** [comment]
Initially, I think we should initially implement a procedure to separately sample data from real and virtual transitions as needed. Not quite sure though, the best implementation strategy to sample from the model (i.e., wrap the model in a virtual environment or not).

However, in the future we may want to mix experiences from both sources to experiment on different sampling approaches when estimating the policy gradients. But this should be a secondary concern for now.

**Comment by angelolovatto** [comment]
One problem that I'm running into is the handling of these "virtual" environments. Basically, the environment would need to have a copy of the policy or its model component, and we would have to update it after every update to the policy (policy here refers to the general `Policy` class in RLlib, which encapsulates the actual policy, critic and model). Another problem is specifying the initial state for such model-based rollouts. As we've seen in MBPO, compounding model errors discourage the use of long model-based rollouts, so ideally we'd like to do short ones from real states encountered by the agent.

I'm beginning to think that, for now, we should handle all model rollouts in the `learn_on_batch` method, and simply use the `SyncSamplesOptimizer` to handle experience collection in the real environments. 

This way, we could implement the learning algorithm much like one would in a simple implementation like [spinningup's ddpg](https://github.com/openai/spinningup/blob/master/spinup/algos/ddpg/ddpg.py), but with all experience collection and initialization separate from the update logic. I believe this is better for debugging in the initial phases of the project.

**Comment by angelolovatto** [comment]
As we've discussed previously, we will probably only sample virtual experience during the policy update and discard them afterwards. Therefore, I'm closing this Issue for now.
