### ISSUE TITLE
Tests for MAPO

### ISSUE THREAD

**Issue by angelolovatto** [thiagopbueno/model-aware-policy-optimization#21]
How should we handle tests for `mapo`? I think it would be nice to have simple tests, at least before closing each Issue/Milestone. That way, we make sure that each functionality is properly implemented and also that we do not break them after adding a new one.

It would be interesting if we could decide upon one that can be used with continuous integration as well. Any thoughts/suggestions?

**Comment by thiagopbueno** [comment]
As for simple tests, I'm a big fan of the [unittest](https://docs.python.org/3/library/unittest.html) framework.. I've never it used but I know people nowadays also love [pytest](https://docs.pytest.org/en/latest/). What do you prefer?

As for CI, what about [travis-ci](https://travis-ci.org/)?

**Comment by angelolovatto** [comment]
I think a combination of `pytest` and `travis-ci` would be good. I have used the former in the past but have no experience with the latter. 

I'll create a rough skeleton of the testing infrastructure and we can build on top of that.

**Comment by angelolovatto** [comment]
PR #22 created the basic test infrastructure, so I'm closing this Issue.
