### ISSUE TITLE
Parameter space exploration

### ISSUE THREAD

**Issue by 0xangelo** [thiagopbueno/model-aware-policy-optimization#30]
What is the best way to implement parameter space exploration?

A few aspects that we have to keep in mind (taken from the [paper](https://arxiv.org/abs/1706.01905)):

* perturbed policies are fixed for a whole rollout
> To achieve structured exploration, we sample from a set of policies by applying additive Gaussian noise to the parameter vector of the current policy. Importantly, the perturbed policy is sampled at the beginning of each episode and kept fixed for the entire rollout

* layer normalization is used and noise scale is shared across all layers
> It is not immediately obvious that deep neural networks, with potentially millions of parameters and complicated nonlinear interactions, can be perturbed in meaningful ways by applying spherical Gaussian noise. However, as recently shown by Salimans et al. (2017), a simple reparameterization of the network achieves exactly this. More concretely, we use layer normalization (Ba et al., 2016) between perturbed layers. Due to this normalizing across activations within a layer, the same perturbation scale can be used across all layers, even though different layers may exhibit different sensitivities to noise.

* adaptive noise scale based on action space divergence
> Parameter space noise requires us to pick a suitable scale σ. This can be problematic since the scale will strongly depend on the specific network architecture, and is likely to vary over time as parameters become more sensitive to noise as learning progresses. Additionally, while it is easy to intuitively grasp the scale of action space noise, it is far harder to understand the scale in parameter space. We propose a simple solution that resolves all aforementioned limitations in an easy and straightforward way. This is achieved by adapting the scale of the parameter space noise over time and relating it to the variance in action space that it induces. More concretely, we can define a distance measure between perturbed and non-perturbed policy in action space and adaptively increase or decrease the parameter space noise depending on whether it is below or above a certain threshold:
![Screen Shot 2019-08-06 at 15 16 39](https://user-images.githubusercontent.com/12701614/62565470-36100680-b85d-11e9-9c9a-ed8857d80a9f.png)

In practice, we double the number of policy variables, since we either have to
1. create noise variables to add and subtract from the policy as needed
2. create a separate policy module to act as the perturbed policy

Personally, I find the second option above to be cleaner and easier to test and implement. What are your thoughts?

**Comment by thiagopbueno** [comment]
Indeed, I was actually about to start a discussion on the add/subtract noise approach. I think it would make a cleaner solution to derive perturbed policies from the original policy before starting the rollouts.

Regarding fixing the policy during the episode and applying layernorm this should be easy to implement (specially considering the 2nd option you mentioned, i.e., separate perturbed policies).

However, it seems that managing adaptive noise scale can be complicated. Does the paper suggest a distance for comparing policies?

**Comment by angelolovatto** [comment]
Yes, the paper suggests distance measures for DQN, DDPG and TRPO. In our case, we should use the DDPG one:

> ![Screen Shot 2019-08-08 at 13 35 31](https://user-images.githubusercontent.com/12701614/62720912-6aaccb00-b9e1-11e9-90cb-43ecf4d161ba.png)
> where E_s[·] is estimated from a batch of states from the replay buffer and N denotes the dimension of the action space (i.e. A ⊂ R^N). It is easy to show that d(π, π +N(0, σ^2 _I_ )) = σ. Setting δ := σ as the adaptive parameter space threshold thus results in effective action space noise that has the same standard deviation as regular Gaussian action space noise.
