### ISSUE TITLE
Build ops for estimating model-aware deterministic policy gradients

### ISSUE THREAD

**Issue by thiagopbueno** [thiagopbueno/model-aware-policy-optimization#4]
Implement n-step and full bootstrap model-aware DPG estimates in PolicyGraph given batch of experiences.

**Comment by thiagopbueno** [comment]
The only things that remains to be implemented here is to incorporate the gradient of the reward function into the mapo gradient...

**Comment by 0xangelo** [comment]
Closed by #60
