### ISSUE TITLE
Allow policy access to the environment

### ISSUE THREAD

**Issue by 0xangelo** [thiagopbueno/model-aware-policy-optimization#54]
For now, I can think of two ways:
* Add a callback on episode start that calls a custom method (maybe `set_current_env`) to set the environment the policy is using. Callbacks are passed through the config (`config["callbacks"]["on_episode_start"]`), but we can add then in `MAPOTrainer` so that they're added every time ([DQN](https://github.com/ray-project/ray/blob/e4854b11f9a032261a3a07029b8492e59002da61/python/ray/rllib/agents/dqn/dqn.py#L168) does this). The callback is called with the following arguments:
```python
            callbacks["on_episode_start"]({
                "env": base_env,
                "policy": policies,
                "episode": episode,
            })
```
* Create a separate environment in the policy using `config["env"]` and `config["env_config"]`. This can be problematic if the environment has some hidden internal state, since in that case the instance used for calculation transitions and the one used for training might behave differently. Nevertheless, we would probably do something similar to what `Trainer` does:
```python
    @override(Trainable)
    def _setup(self, config):
        env = self._env_id
        if env:
            config["env"] = env
            if _global_registry.contains(ENV_CREATOR, env):
                self.env_creator = _global_registry.get(ENV_CREATOR, env)
            else:
                import gym  # soft dependency
                self.env_creator = lambda env_config: gym.make(env)
        else:
            self.env_creator = lambda env_config: None

```

_Originally posted by @angelolovatto in https://github.com/thiagopbueno/model-aware-policy-optimization/pull/50/review_comment/create_

**Comment by thiagopbueno** [comment]
If `base_env` in the callback solution is an already-instantiated env object then the callback method would be a simpler alternative I guess... but if it is just a reference to the env class then maybe the second method might be simpler...
