### ISSUE TITLE
Fix the sign of model_aware_policy_loss in order to minimize it

### ISSUE THREAD

**Issue by thiagopbueno** [thiagopbueno/model-aware-policy-optimization#81]
It seems that we are currently "maximizing" the mapo_loss instead of minimizing... 

I guess we should add a unary minus sign before the reduce_mean in `losses.actor_model_aware_loss`:

```python
model_aware_policy_loss = - tf.reduce_mean(
        reward + gamma * tf.reduce_mean(next_state_log_prob * next_state_value, axis=0)
    )
```

instead of (the current version):

```python
model_aware_policy_loss = tf.reduce_mean(
        reward + gamma * tf.reduce_mean(next_state_log_prob * next_state_value, axis=0)
    )
```

What do you think @angelolovatto ?

Try to run the following experiment with `--use-true-dynamics`  (with and without the minus sign):

```bash
mapo --run MAPO --env Navigation-v0 --use-true-dynamics --config-actor-net actor-1024-relu.json --config-critic-net critic-1024-relu.json --actor-lr 1e-4 --critic-lr 1e-4 --sample-batch-size 1 --train-batch-size 2048 --num-samples 5 --name nav0-mapo-true-dynamics-fcnet-1024
```

**Comment by 0xangelo** [comment]
Hmm, that was a big oversight on my part. Will make sure to fix this right now. Thanks!
